USE [SQLWEEKRECIFE]
GO

IF EXISTS ( SELECT 1 FROM SYS.tables WHERE NAME = 'TB_CARGO')
DROP TABLE dbo.TB_CARGO 
GO

CREATE TABLE dbo.TB_CARGO 
(
CD_CARGO  VARCHAR(2000) NOT NULL 
, DS_CARGO VARCHAR(100)
)
GO

ALTER TABLE dbo.TB_CARGO ADD CONSTRAINT [PK_TB_CARGO] PRIMARY KEY (CD_CARGO)
GO

INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('1','PRESIDENTE');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('2','VICE-PRESIDENTE');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('3','GOVERNADOR');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('4','VICE-GOVERNADOR');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('5','SENADOR');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('6','DEPUTADO FEDERAL');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('7','DEPUTADO ESTADUAL');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('8','DEPUTADO DISTRITAL');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('9','1º SUPLENTE');
INSERT INTO dbo.TB_CARGO (CD_CARGO , DS_CARGO) VALUES ('10','2º SUPLENTE');

ALTER TABLE dbo.TB_CANDIDATO ADD CONSTRAINT [FK_TB_CANDIDATO_TB_CARGO]
FOREIGN KEY (CD_CARGO) REFERENCES dbo.TB_CARGO (CD_CARGO)
GO

/*

TRUNCATE TABLE dbo.TB_CANDIDATO

DELETE
FROM dbo.TB_CARGO
WHERE CD_CARGO >= 9

*/